version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: ecs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecs_mapper
      MYSQL_USER: ecs_user
      MYSQL_PASSWORD: ecspass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]

